name: Ping Supabase

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Ping Supabase
        run: curl --fail -X POST https://purplecat-stayzen.vercel.app/api/supabase
